# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setTabletTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #0f111a;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #2d2f3a;\n"
"    border-radius: 8px;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #1a1d29;\n"
"    color: #ffffff;\n"
"    border: 1px solid #2d2f3a;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #0b0f19;\n"
"    color: #00ff9d;\n"
"    font-family: Consolas;\n"
"    font-size: 13px;\n"
"    border: 1px solid #2d2f3a;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1b5fbf;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setStyleSheet("font-size:24px;font-weight:bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_main.addWidget(self.titleLabel)
        self.groupBox_keys = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_keys.setStyleSheet("font-size:18px;")
        self.groupBox_keys.setObjectName("groupBox_keys")
        self.gridLayout_keys = QtWidgets.QGridLayout(self.groupBox_keys)
        self.gridLayout_keys.setObjectName("gridLayout_keys")
        self.label_w = QtWidgets.QLabel(self.groupBox_keys)
        self.label_w.setObjectName("label_w")
        self.gridLayout_keys.addWidget(self.label_w, 0, 0, 1, 1)
        self.lineEdit_w = QtWidgets.QLineEdit(self.groupBox_keys)
        self.lineEdit_w.setObjectName("lineEdit_w")
        self.gridLayout_keys.addWidget(self.lineEdit_w, 0, 1, 1, 1)
        self.label_w_status = QtWidgets.QLabel(self.groupBox_keys)
        self.label_w_status.setStyleSheet("color: #00ff9d;")
        self.label_w_status.setObjectName("label_w_status")
        self.gridLayout_keys.addWidget(self.label_w_status, 0, 2, 1, 1)
        self.label_q = QtWidgets.QLabel(self.groupBox_keys)
        self.label_q.setObjectName("label_q")
        self.gridLayout_keys.addWidget(self.label_q, 1, 0, 1, 1)
        self.lineEdit_q = QtWidgets.QLineEdit(self.groupBox_keys)
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.gridLayout_keys.addWidget(self.lineEdit_q, 1, 1, 1, 1)
        self.label_q_status = QtWidgets.QLabel(self.groupBox_keys)
        self.label_q_status.setStyleSheet("color: #00ff9d;")
        self.label_q_status.setObjectName("label_q_status")
        self.gridLayout_keys.addWidget(self.label_q_status, 1, 2, 1, 1)
        self.label_r = QtWidgets.QLabel(self.groupBox_keys)
        self.label_r.setObjectName("label_r")
        self.gridLayout_keys.addWidget(self.label_r, 2, 0, 1, 1)
        self.lineEdit_r = QtWidgets.QLineEdit(self.groupBox_keys)
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.gridLayout_keys.addWidget(self.lineEdit_r, 2, 1, 1, 1)
        self.label_r_status = QtWidgets.QLabel(self.groupBox_keys)
        self.label_r_status.setStyleSheet("color: #00ff9d;")
        self.label_r_status.setObjectName("label_r_status")
        self.gridLayout_keys.addWidget(self.label_r_status, 2, 2, 1, 1)
        self.layout_key_buttons = QtWidgets.QHBoxLayout()
        self.layout_key_buttons.setObjectName("layout_key_buttons")
        self.btnValidate = QtWidgets.QPushButton(self.groupBox_keys)
        self.btnValidate.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1b5fbf;\n"
"}")
        self.btnValidate.setObjectName("btnValidate")
        self.layout_key_buttons.addWidget(self.btnValidate)
        self.btnAutoGenerate = QtWidgets.QPushButton(self.groupBox_keys)
        self.btnAutoGenerate.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1b5fbf;\n"
"}")
        self.btnAutoGenerate.setObjectName("btnAutoGenerate")
        self.layout_key_buttons.addWidget(self.btnAutoGenerate)
        self.gridLayout_keys.addLayout(self.layout_key_buttons, 3, 0, 1, 3)
        self.verticalLayout_main.addWidget(self.groupBox_keys)
        self.layout_io = QtWidgets.QHBoxLayout()
        self.layout_io.setObjectName("layout_io")
        self.groupBox_input = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_input.setStyleSheet("font-size:18px")
        self.groupBox_input.setObjectName("groupBox_input")
        self.layout_input = QtWidgets.QVBoxLayout(self.groupBox_input)
        self.layout_input.setObjectName("layout_input")
        self.inputText = QtWidgets.QTextEdit(self.groupBox_input)
        self.inputText.setObjectName("inputText")
        self.layout_input.addWidget(self.inputText)
        self.layout_io.addWidget(self.groupBox_input)
        self.groupBox_output = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_output.setStyleSheet("font-size:18px")
        self.groupBox_output.setObjectName("groupBox_output")
        self.layout_output = QtWidgets.QVBoxLayout(self.groupBox_output)
        self.layout_output.setObjectName("layout_output")
        self.outputText = QtWidgets.QTextEdit(self.groupBox_output)
        self.outputText.setObjectName("outputText")
        self.layout_output.addWidget(self.outputText)
        self.layout_io.addWidget(self.groupBox_output)
        self.verticalLayout_main.addLayout(self.layout_io)
        self.layout_actions = QtWidgets.QHBoxLayout()
        self.layout_actions.setObjectName("layout_actions")
        self.encryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1b5fbf;\n"
"}")
        self.encryptBtn.setObjectName("encryptBtn")
        self.layout_actions.addWidget(self.encryptBtn)
        self.decryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1b5fbf;\n"
"}")
        self.decryptBtn.setObjectName("decryptBtn")
        self.layout_actions.addWidget(self.decryptBtn)
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setStyleSheet("QPushButton {\n"
"    background-color: #2d89ef;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1b5fbf;\n"
"}")
        self.resetBtn.setObjectName("resetBtn")
        self.layout_actions.addWidget(self.resetBtn)
        self.verticalLayout_main.addLayout(self.layout_actions)
        self.groupBox_log = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_log.setStyleSheet("font-size:18px;")
        self.groupBox_log.setObjectName("groupBox_log")
        self.layout_log = QtWidgets.QVBoxLayout(self.groupBox_log)
        self.layout_log.setObjectName("layout_log")
        self.logText = QtWidgets.QTextEdit(self.groupBox_log)
        self.logText.setObjectName("logText")
        self.layout_log.addWidget(self.logText)
        self.verticalLayout_main.addWidget(self.groupBox_log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RYUKZAK SHIFRLASH ALGORITMI"))
        self.titleLabel.setText(_translate("MainWindow", "RYUKZAK SHIFRLASH ALGORITMI"))
        self.groupBox_keys.setTitle(_translate("MainWindow", "Parametrlar"))
        self.label_w.setText(_translate("MainWindow", "w:"))
        self.lineEdit_w.setPlaceholderText(_translate("MainWindow", "2 3 7 15"))
        self.label_w_status.setText(_translate("MainWindow", "❌"))
        self.label_q.setText(_translate("MainWindow", "q:"))
        self.lineEdit_q.setPlaceholderText(_translate("MainWindow", "28"))
        self.label_q_status.setText(_translate("MainWindow", "❌"))
        self.label_r.setText(_translate("MainWindow", "r:"))
        self.lineEdit_r.setPlaceholderText(_translate("MainWindow", "11"))
        self.label_r_status.setText(_translate("MainWindow", "❌"))
        self.btnValidate.setText(_translate("MainWindow", "Parametrlarni tekshirish"))
        self.btnAutoGenerate.setText(_translate("MainWindow", "Parametrlarni generatsiya qilish"))
        self.groupBox_input.setTitle(_translate("MainWindow", "Ochiq matn"))
        self.groupBox_output.setTitle(_translate("MainWindow", "Shifr matn"))
        self.encryptBtn.setText(_translate("MainWindow", "Shifrlash"))
        self.decryptBtn.setText(_translate("MainWindow", "Deshifrlash"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))
        self.groupBox_log.setTitle(_translate("MainWindow", "Log"))
